### ISSUE TITLE
synchronisation vs synchronization

### ISSUE THREAD

**Issue by bmlong137** [Acosix/alfresco-keycloak#16]
The Markdown documentation refers to property `synchronisation`, but the code appears to use `synchronization`.

**Comment by AFaust** [comment]
Ah, yes. I generally try to use British spelling (at least where I am aware of a difference), but since Alfresco often uses US spelling to which I try to adhere when it helps make configuration properties consistent, this does not make it easy sometimes to write documentation in a consistent manner.
