### ISSUE TITLE
Synchronisation questions

### ISSUE THREAD

**Issue by howkymike** [Acosix/alfresco-keycloak#18]
Hello @AFaust 
I've been playing with your awesome addon for some time now but I have two questions about synchronisation.
1. As I understand, synchronisation works unidirectional - from Keycloak to Alfresco. Is it possible to do it bi-directionally?
2. What about synchronizing currently existing users? Is it overriding them? I.e. there is the userX in Alfresco, then we create userX within Keycloak (but with different properties), how these accounts are merged? 
I'm asking because of the migration of the alfresco users to Keycloak - I thought it would be a big problem but it seems like I just have to create those users in Keycloak and everything will be fine (the users would only need to change their password). And the second thing is that after creating a user in Alfresco I can immediately assign it to proper sites, roles, groups. But if I create users in Keycloak, it is impossible. So it would be a nice workaround.

**Comment by AFaust** [comment]
So the current synchronisation functionality works based on what Alfresco already has in place for LDAP / AD synchronisation, effectively only adding the connector component for Keycloak. So yes, it is unidirectional. But technically speaking, the Keycloak ReST APIs would allow for some kind of sync from Alfresco to Keycloak, and it would only require an extension to the [IDMClient](https://github.com/Acosix/alfresco-keycloak/blob/master/repository/src/main/java/de/acosix/alfresco/keycloak/repo/client/IDMClient.java) to expose such capabilities to code in Alfresco, e.g. for a module component which synchronises users / groups from Alfresco to Keycloak upon first installation of Keycloak, so they can subsequently be managed there.

As for question 2, this works like in a similar scenario with LDAP / AD because it reuses Alfresco's existing functionality. That means that existing users are handled depending on the order of the subsystems in the authentication chain. If Keycloak comes before any other subsystem (or before the subsystem which used to manage the user / group before), than Alfresco will update the element in Alfresco and mark it as originating from Keycloak.
As for question 2.5 (about initial site / roles / groups assignment), I see multiple options.

- you could use intermediary groups in Keycloak that are synchronised to Alfresco to assign users to sites, roles, groups without having to assign the users by name
- you could use [roles in Keycloak which are mapped](https://github.com/Acosix/alfresco-keycloak/blob/master/repository/src/main/globalConfig/subsystems/Authentication/keycloak/keycloak-authentication.properties#L72) to site role groups so that a user has all the privileges at runtime that come with such a membership, with the only difference being that they are not "actually" part of the group (e.g. other people / background processing will not see them as members, as the mapping is only applied for web requests that the specific user does)
- when/if PR #17 is included, there would be an optional feature which could sync groups / roles "on first login" from the token, essentially turning the previous point into a persistent state where the membership would be real and visible to other people / background processing
- you could have groups in Keycloak that are named identically to the internal site membership role groups (`site_<siteName>_<roleName>` e.g. `site_swsdp_SiteManager`), and upon synchronization, the site role memberships from Keycloak would be carried over to Alfresco - you would have to be careful about potential side effects, e.g. the group in Keycloak should only be created / synchronised after creating the site as otherwise Alfresco will stumble (if the IDMClient allowed creating groups in Keycloak, this could even be automated to a degree via a behaviour which duplicates the site role groups in Keycloak, where you can then assign them, and those assignments would be synched to Alfresco the next time the synch runs)

**Comment by howkymike** [comment]
Thank you very much, now everything is clear. I'll think about this IDMClient extension.

**Comment by howkymike** [comment]
Hi @AFaust ,
sorry for bothering you again but I have one more question. I tried to assign a Site group in Keycloak (just like you said) but it does not work. 
In Alfresco I have a "codes" site. In Keycloak I created the "site_codes_SiteManger" group and added a user to it. Then I logged in but I did not have access to the site and in the Alfresco admin console I saw a weird group name. I guess Keycloak sends its own group ID instead of just a group name. I tried to explicitly set group ID in Keycloak (via REST API) but with no success.
![Screenshot from 2021-09-07 14-25-29](https://user-images.githubusercontent.com/34208123/132348292-52b1c3ba-dc1a-4614-8a4a-af0d91c549bc.png). 
Did you faced the same issue or do you know how to resolve it?
