### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by maxodoble** [Acosix/alfresco-keycloak#7]
tried building:

`mvn clean install`

getting error:

`[ERROR] Failed to execute goal de.acosix.maven:jshint-plugin:1.1.0:jshint (Validate Webapp) on project de.acosix.alfresco.keycloak.repo: Execution Validate Webapp of goal de.acosix.maven:jshint-plugin:1.1.0:jshint failed: Plugin de.acosix.maven:jshint-plugin:1.1.0 or one of its dependencies could not be resolved: Could not find artifact de.acosix.alfresco.maven:de.acosix.alfresco.maven.definitions:jar:1.3.4-SNAPSHOT in ossrh (https://oss.sonatype.org/content/repositories/snapshots) -> [Help 1]
`

is master not ready for building yet?

thanks,

max

**Comment by AFaust** [comment]
Same issue as the one you reported in the other project. The parent POM 1.3.4 release had an issue (which I don't notice locally because SNAPSHOTS are automatically deleted in OSSRH but not in my mirror). Commit https://github.com/Acosix/alfresco-keycloak/commit/3497bbe25762c98c77f664e9bb2d1bd133e80047 switches to latest parent POM SNAPSHOT

**Comment by maxodoble** [comment]
Thank you very much,

both projects are building without errors now!
